function [nassCropNames,faoCropNames]=NASSCropNameList;


% Sample NASS crop names
nassCropNames = {'Corn', 'Wheat', 'Soybeans', 'Rice', ...
    'Barley', 'Oats', 'Cotton', 'Peanuts', 'Sorghum', ...
    'Canola','Oats',...
    'Potatoes','Rye','Sugarcane','sweet potatoes'};

% Sample FAO crop names corresponding to NASS crop names
faoCropNames = {'Maize', 'Wheat', 'Soybean', 'Rice',...
    'Barley', 'Oats', 'Cotton', 'groundnut', 'Sorghum', ...
    'Rapeseed','Oats',...
    'Potato','Rye','Sugarcane','sweetpotato'};


return

% longer list with some removals (beans, sunflower)
% Apples - strange units

% Sample NASS crop names
nassCropNames = {'Corn', 'Wheat', 'Soybeans', 'Rice', ...
    'Barley', 'Oats', 'Cotton', 'Peanuts', 'Sorghum', 'Sunflower', ...
    'Canola','Apples','Beans','Grape','Millet','Oats','Orange',...
    'Potatoes','Rye','Sugarbeet','Sugarcane','sweet potatoes','tomatoes'};

% Sample FAO crop names corresponding to NASS crop names
faoCropNames = {'Maize', 'Wheat', 'Soybean', 'Rice',...
    'Barley', 'Oats', 'Cotton', 'groundnut', 'Sorghum', 'Sunflower', ...
    'Rapeseed','Apple','Bean','Grape','Millet','Oats','Orange',...
    'Potato','Rye','Sugarbeet','Sugarcane','sweetpotato','tomato'};