function UNSDMethodology = importUNRegionData(workbookFile, sheetName, dataLines)
 %importUNRegionData Import data from a spreadsheet
 %
 % Matlab wrote this function for me
 %
 % underlying data downloaded Fri July 11 from https://unstats.un.org/unsd/methodology/m49/overview/
 %
%  UNSDMETHODOLOGY = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  UNSDMETHODOLOGY = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  UNSDMETHODOLOGY = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  UNSDMethodology = importUNRegionData("UNSD — Methodology.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jul-2025 15:10:30

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["GlobalCode", "GlobalName", "RegionCode", "RegionName", "SubregionCode", "SubregionName", "IntermediateRegionCode", "IntermediateRegionName", "CountryOrArea", "M49Code", "ISOalpha2Code", "ISOalpha3Code", "LeastDevelopedCountriesLDC", "LandLockedDevelopingCountriesLLDC", "SmallIslandDevelopingStatesSIDS"];
opts.VariableTypes = ["double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "string", "double", "string", "string", "categorical", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["CountryOrArea", "ISOalpha2Code", "ISOalpha3Code"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["GlobalName", "RegionName", "SubregionName", "IntermediateRegionName", "CountryOrArea", "ISOalpha2Code", "ISOalpha3Code", "LeastDevelopedCountriesLDC", "LandLockedDevelopingCountriesLLDC", "SmallIslandDevelopingStatesSIDS"], "EmptyFieldRule", "auto");

% Import the data
UNSDMethodology = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    UNSDMethodology = [UNSDMethodology; tb]; %#ok<AGROW>
end

end